FROM python:3.12-slim

ARG VERSION=latest
ENV APP_VERSION=$VERSION

WORKDIR /app

RUN apt-get update && apt-get install -y gcc curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir watchdog[watchmedo] pytest pytest-watch ipython

ENV FLASK_DEBUG=1
ENV FLASK_APP=src/main.py

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--reload"]
CMD []
