FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir watchdog[watchmedo] pytest pytest-watch ipython

COPY src/ ./src/

# First copy example, and then use user system prompt if it can be found
COPY .systemprompt.example /app/.systemprompt
COPY .systempromp[t] /app/.systemprompt

ENV FLASK_DEBUG=1
ENV FLASK_APP=src/main.py

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=8000", "--reload"]
CMD []
